[package]
name = "draconic-conformance"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
draconic-parser.workspace = true
draconic-check.workspace = true
draconic-ir.workspace = true
draconic-backend-js.workspace = true
draconic-backend-llvm.workspace = true
