[package]
name = "draconic-conformance"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
draconic-frontend.workspace = true
draconic-backend-js.workspace = true
draconic-backend-llvm.workspace = true

[dev-dependencies]
draconic-parser.workspace = true
draconic-check.workspace = true
