[package]
name = "draconic-integration-tests"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dev-dependencies]
draconic-frontend.workspace = true
draconic-ir.workspace = true
draconic-backend-js.workspace = true
draconic-backend-llvm.workspace = true
draconic-lsp.workspace = true
draconic-diagnostics.workspace = true
