[package]
name = "draconic-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "draconic"
path = "src/main.rs"

[dependencies]
draconic-parser.workspace = true
draconic-check.workspace = true
draconic-ir.workspace = true
draconic-backend-js.workspace = true
draconic-backend-llvm.workspace = true
draconic-diagnostics.workspace = true
draconic-conformance.workspace = true
