[package]
name = "draconic-backend-js"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
draconic-ast.workspace = true
draconic-check.workspace = true
draconic-ir.workspace = true
draconic-diagnostics.workspace = true
draconic-runtime.workspace = true

[dev-dependencies]
draconic-frontend.workspace = true
