use super::abi_host::*;
use super::abi_host_io::*;
use super::abi_host_net::*;
use super::AbiFn;

pub const HOST_HANDLE_IS_VALID_SYMBOL: &str = HOST_HANDLE_IS_VALID.symbol;
pub const HOST_HANDLE_CLOSE_SYMBOL: &str = HOST_HANDLE_CLOSE.symbol;
pub const HOST_PATH_FROM_UTF8_SYMBOL: &str = HOST_PATH_FROM_UTF8.symbol;
pub const HOST_PATH_FREE_SYMBOL: &str = HOST_PATH_FREE.symbol;
pub const HOST_BYTES_FROM_RAW_SYMBOL: &str = HOST_BYTES_FROM_RAW.symbol;
pub const HOST_BYTES_VIEW_SYMBOL: &str = HOST_BYTES_VIEW.symbol;
pub const HOST_BYTES_ALLOC_SYMBOL: &str = HOST_BYTES_ALLOC.symbol;
pub const HOST_BYTES_STORAGE_FREE_SYMBOL: &str = HOST_BYTES_STORAGE_FREE.symbol;
pub const HOST_BYTES_COPY_IN_SYMBOL: &str = HOST_BYTES_COPY_IN.symbol;
pub const HOST_BYTES_COPY_OUT_SYMBOL: &str = HOST_BYTES_COPY_OUT.symbol;
pub const HOST_PROCESS_SET_ARGV_SYMBOL: &str = HOST_PROCESS_SET_ARGV.symbol;
pub const HOST_PROCESS_USER_ARGC_SYMBOL: &str = HOST_PROCESS_USER_ARGC.symbol;
pub const HOST_PROCESS_USER_ARG_SYMBOL: &str = HOST_PROCESS_USER_ARG.symbol;
pub const HOST_ENV_GET_SYMBOL: &str = HOST_ENV_GET.symbol;
pub const HOST_ENV_SET_SYMBOL: &str = HOST_ENV_SET.symbol;
pub const HOST_ENV_DELETE_SYMBOL: &str = HOST_ENV_DELETE.symbol;
pub const HOST_PROCESS_EXIT_SYMBOL: &str = HOST_PROCESS_EXIT.symbol;
pub const HOST_PROCESS_SET_EXIT_CODE_SYMBOL: &str = HOST_PROCESS_SET_EXIT_CODE.symbol;
pub const HOST_PROCESS_GET_EXIT_CODE_SYMBOL: &str = HOST_PROCESS_GET_EXIT_CODE.symbol;
pub const HOST_PROCESS_PID_SYMBOL: &str = HOST_PROCESS_PID.symbol;
pub const HOST_PROCESS_PPID_SYMBOL: &str = HOST_PROCESS_PPID.symbol;
pub const HOST_CWD_SYMBOL: &str = HOST_CWD.symbol;
pub const HOST_CHDIR_SYMBOL: &str = HOST_CHDIR.symbol;
pub const HOST_HOSTNAME_SYMBOL: &str = HOST_HOSTNAME.symbol;
pub const HOST_OS_TYPE_SYMBOL: &str = HOST_OS_TYPE.symbol;
pub const HOST_OS_ARCH_SYMBOL: &str = HOST_OS_ARCH.symbol;
pub const HOST_SIGNAL_WATCH_SYMBOL: &str = HOST_SIGNAL_WATCH.symbol;
pub const HOST_SIGNAL_RAISE_SYMBOL: &str = HOST_SIGNAL_RAISE.symbol;
pub const HOST_SIGNAL_POLL_SYMBOL: &str = HOST_SIGNAL_POLL.symbol;
pub const HOST_NOW_MS_SYMBOL: &str = HOST_NOW_MS.symbol;
pub const HOST_MONOTONIC_MS_SYMBOL: &str = HOST_MONOTONIC_MS.symbol;
pub const HOST_STDOUT_WRITE_SYMBOL: &str = HOST_STDOUT_WRITE.symbol;
pub const HOST_STDERR_WRITE_SYMBOL: &str = HOST_STDERR_WRITE.symbol;
pub const HOST_STDIN_READ_LINE_SYMBOL: &str = HOST_STDIN_READ_LINE.symbol;
pub const HOST_STDIN_READ_BYTES_SYMBOL: &str = HOST_STDIN_READ_BYTES.symbol;
pub const HOST_PATH_NORMALIZE_SYMBOL: &str = HOST_PATH_NORMALIZE.symbol;
pub const HOST_PATH_JOIN_SYMBOL: &str = HOST_PATH_JOIN.symbol;
pub const HOST_PATH_DIRNAME_SYMBOL: &str = HOST_PATH_DIRNAME.symbol;
pub const HOST_PATH_BASENAME_SYMBOL: &str = HOST_PATH_BASENAME.symbol;
pub const HOST_PATH_EXTNAME_SYMBOL: &str = HOST_PATH_EXTNAME.symbol;
pub const HOST_PATH_IS_ABSOLUTE_SYMBOL: &str = HOST_PATH_IS_ABSOLUTE.symbol;
pub const HOST_PATH_RESOLVE_SYMBOL: &str = HOST_PATH_RESOLVE.symbol;
pub const HOST_FS_READ_FILE_SYMBOL: &str = HOST_FS_READ_FILE.symbol;
pub const HOST_FS_READ_TEXT_SYMBOL: &str = HOST_FS_READ_TEXT.symbol;
pub const HOST_FS_WRITE_FILE_SYMBOL: &str = HOST_FS_WRITE_FILE.symbol;
pub const HOST_FS_APPEND_FILE_SYMBOL: &str = HOST_FS_APPEND_FILE.symbol;
pub const HOST_FS_WRITE_TEXT_SYMBOL: &str = HOST_FS_WRITE_TEXT.symbol;
pub const HOST_FS_APPEND_TEXT_SYMBOL: &str = HOST_FS_APPEND_TEXT.symbol;
pub const HOST_FS_EXISTS_SYMBOL: &str = HOST_FS_EXISTS.symbol;
pub const HOST_FS_STAT_SYMBOL: &str = HOST_FS_STAT.symbol;
pub const HOST_FS_MKDIR_SYMBOL: &str = HOST_FS_MKDIR.symbol;
pub const HOST_FS_MKDIR_ALL_SYMBOL: &str = HOST_FS_MKDIR_ALL.symbol;
pub const HOST_FS_READDIR_SYMBOL: &str = HOST_FS_READDIR.symbol;
pub const HOST_FS_RMDIR_SYMBOL: &str = HOST_FS_RMDIR.symbol;
pub const HOST_FS_REMOVE_FILE_SYMBOL: &str = HOST_FS_REMOVE_FILE.symbol;
pub const HOST_FS_RENAME_FILE_SYMBOL: &str = HOST_FS_RENAME_FILE.symbol;
pub const HOST_FS_COPY_FILE_SYMBOL: &str = HOST_FS_COPY_FILE.symbol;
pub const HOST_FS_OPEN_SYMBOL: &str = HOST_FS_OPEN.symbol;
pub const HOST_FS_HANDLE_READ_SYMBOL: &str = HOST_FS_HANDLE_READ.symbol;
pub const HOST_FS_HANDLE_WRITE_SYMBOL: &str = HOST_FS_HANDLE_WRITE.symbol;
pub const HOST_FS_HANDLE_SEEK_SYMBOL: &str = HOST_FS_HANDLE_SEEK.symbol;
pub const HOST_TCP_LISTEN_SYMBOL: &str = HOST_TCP_LISTEN.symbol;
pub const HOST_TCP_LOCAL_PORT_SYMBOL: &str = HOST_TCP_LOCAL_PORT.symbol;
pub const HOST_TCP_ACCEPT_SYMBOL: &str = HOST_TCP_ACCEPT.symbol;
pub const HOST_TCP_CONNECT_SYMBOL: &str = HOST_TCP_CONNECT.symbol;
pub const HOST_TCP_PEER_PORT_SYMBOL: &str = HOST_TCP_PEER_PORT.symbol;
pub const HOST_TCP_PEER_ADDRESS_SYMBOL: &str = HOST_TCP_PEER_ADDRESS.symbol;
pub const HOST_TCP_READ_SYMBOL: &str = HOST_TCP_READ.symbol;
pub const HOST_TCP_WRITE_SYMBOL: &str = HOST_TCP_WRITE.symbol;
pub const HOST_TCP_SHUTDOWN_SYMBOL: &str = HOST_TCP_SHUTDOWN.symbol;
pub const HOST_TCP_SET_NONBLOCKING_SYMBOL: &str = HOST_TCP_SET_NONBLOCKING.symbol;
pub const HOST_IO_WAIT_SYMBOL: &str = HOST_IO_WAIT.symbol;
pub const HOST_IO_CANCEL_SYMBOL: &str = HOST_IO_CANCEL.symbol;
pub const HOST_IO_PENDING_SYMBOL: &str = HOST_IO_PENDING.symbol;
pub const HOST_IO_POLL_SYMBOL: &str = HOST_IO_POLL.symbol;
pub const HOST_TCP_ACCEPT_ASYNC_SYMBOL: &str = HOST_TCP_ACCEPT_ASYNC.symbol;
pub const HOST_TCP_CONNECT_ASYNC_SYMBOL: &str = HOST_TCP_CONNECT_ASYNC.symbol;
pub const HOST_TCP_READ_ASYNC_SYMBOL: &str = HOST_TCP_READ_ASYNC.symbol;
pub const HOST_TCP_WRITE_ASYNC_SYMBOL: &str = HOST_TCP_WRITE_ASYNC.symbol;
pub const HOST_UDP_BIND_SYMBOL: &str = HOST_UDP_BIND.symbol;
pub const HOST_UDP_LOCAL_PORT_SYMBOL: &str = HOST_UDP_LOCAL_PORT.symbol;
pub const HOST_UDP_SENDTO_SYMBOL: &str = HOST_UDP_SENDTO.symbol;
pub const HOST_UDP_RECVFROM_SYMBOL: &str = HOST_UDP_RECVFROM.symbol;
pub const HOST_DNS_LOOKUP_SYMBOL: &str = HOST_DNS_LOOKUP.symbol;
pub const HOST_HTTP_PARSE_REQUEST_SYMBOL: &str = HOST_HTTP_PARSE_REQUEST.symbol;
pub const HOST_HTTP_REQUEST_HEADER_SYMBOL: &str = HOST_HTTP_REQUEST_HEADER.symbol;
pub const HOST_HTTP_WRITE_RESPONSE_SYMBOL: &str = HOST_HTTP_WRITE_RESPONSE.symbol;
pub const HOST_HTTP_SERVE_STATIC_SYMBOL: &str = HOST_HTTP_SERVE_STATIC.symbol;
pub const HOST_HTTP_WRITE_REQUEST_SYMBOL: &str = HOST_HTTP_WRITE_REQUEST.symbol;
pub const HOST_HTTP_PARSE_RESPONSE_SYMBOL: &str = HOST_HTTP_PARSE_RESPONSE.symbol;
pub const HOST_HTTP_RESPONSE_HEADER_SYMBOL: &str = HOST_HTTP_RESPONSE_HEADER.symbol;
pub const HOST_WORKER_SPAWN_SYMBOL: &str = HOST_WORKER_SPAWN.symbol;
pub const HOST_WORKER_JOIN_SYMBOL: &str = HOST_WORKER_JOIN.symbol;
pub const HOST_WORKER_TERMINATE_SYMBOL: &str = HOST_WORKER_TERMINATE.symbol;
pub const HOST_WORKER_OS_THREAD_SYMBOL: &str = HOST_WORKER_OS_THREAD.symbol;
pub const HOST_CHANNEL_MAKE_SYMBOL: &str = HOST_CHANNEL_MAKE.symbol;
pub const HOST_CHANNEL_SEND_F64_SYMBOL: &str = HOST_CHANNEL_SEND_F64.symbol;
pub const HOST_CHANNEL_SEND_STR_SYMBOL: &str = HOST_CHANNEL_SEND_STR.symbol;
pub const HOST_CHANNEL_SEND_BOOL_SYMBOL: &str = HOST_CHANNEL_SEND_BOOL.symbol;
pub const HOST_CHANNEL_RECV_F64_SYMBOL: &str = HOST_CHANNEL_RECV_F64.symbol;
pub const HOST_CHANNEL_RECV_STR_SYMBOL: &str = HOST_CHANNEL_RECV_STR.symbol;
pub const HOST_CHANNEL_RECV_BOOL_SYMBOL: &str = HOST_CHANNEL_RECV_BOOL.symbol;
pub const HOST_CHANNEL_SEND_OBJ_SYMBOL: &str = HOST_CHANNEL_SEND_OBJ.symbol;
pub const HOST_CHANNEL_RECV_OBJ_SYMBOL: &str = HOST_CHANNEL_RECV_OBJ.symbol;
pub const HOST_WS_HANDSHAKE_RESPONSE_SYMBOL: &str = HOST_WS_HANDSHAKE_RESPONSE.symbol;
pub const HOST_WS_ENCODE_TEXT_SYMBOL: &str = HOST_WS_ENCODE_TEXT.symbol;
pub const HOST_WS_ENCODE_BINARY_SYMBOL: &str = HOST_WS_ENCODE_BINARY.symbol;
pub const HOST_WS_ENCODE_CLOSE_SYMBOL: &str = HOST_WS_ENCODE_CLOSE.symbol;
pub const HOST_WS_ENCODE_PING_SYMBOL: &str = HOST_WS_ENCODE_PING.symbol;
pub const HOST_WS_ENCODE_PONG_SYMBOL: &str = HOST_WS_ENCODE_PONG.symbol;
pub const HOST_WS_DECODE_FRAME_SYMBOL: &str = HOST_WS_DECODE_FRAME.symbol;
pub const HOST_WS_CLIENT_HANDSHAKE_REQUEST_SYMBOL: &str = HOST_WS_CLIENT_HANDSHAKE_REQUEST.symbol;
pub const HOST_WS_CLIENT_CHECK_ACCEPT_SYMBOL: &str = HOST_WS_CLIENT_CHECK_ACCEPT.symbol;
pub const HOST_WS_ENCODE_TEXT_CLIENT_SYMBOL: &str = HOST_WS_ENCODE_TEXT_CLIENT.symbol;
pub const HOST_HTTP2_CLIENT_PREFACE_SYMBOL: &str = HOST_HTTP2_CLIENT_PREFACE.symbol;
pub const HOST_HTTP2_SERVER_PREFACE_SYMBOL: &str = HOST_HTTP2_SERVER_PREFACE.symbol;
pub const HOST_HTTP2_SETTINGS_ACK_SYMBOL: &str = HOST_HTTP2_SETTINGS_ACK.symbol;
pub const HOST_HTTP2_ENCODE_REQUEST_SYMBOL: &str = HOST_HTTP2_ENCODE_REQUEST.symbol;
pub const HOST_HTTP2_ENCODE_RESPONSE_SYMBOL: &str = HOST_HTTP2_ENCODE_RESPONSE.symbol;
pub const HOST_HTTP2_PARSE_REQUEST_SYMBOL: &str = HOST_HTTP2_PARSE_REQUEST.symbol;
pub const HOST_HTTP2_PARSE_RESPONSE_SYMBOL: &str = HOST_HTTP2_PARSE_RESPONSE.symbol;
pub const HOST_HTTP2_CLIENT_OPEN_SYMBOL: &str = HOST_HTTP2_CLIENT_OPEN.symbol;
pub const HOST_HTTP2_SERVER_REPLY_SYMBOL: &str = HOST_HTTP2_SERVER_REPLY.symbol;
pub const HOST_TLS_CLIENT_WRAP_SYMBOL: &str = HOST_TLS_CLIENT_WRAP.symbol;
pub const HOST_TLS_SERVER_WRAP_SYMBOL: &str = HOST_TLS_SERVER_WRAP.symbol;
pub const HOST_TLS_READ_SYMBOL: &str = HOST_TLS_READ.symbol;
pub const HOST_TLS_WRITE_SYMBOL: &str = HOST_TLS_WRITE.symbol;

/// Host Runtime ABI symbols (H00.02 scaffold + H00.03 bytes + H01–H11.01).
pub const HOST_SYMBOLS: &[&str] = &[
    HOST_HANDLE_IS_VALID_SYMBOL,
    HOST_HANDLE_CLOSE_SYMBOL,
    HOST_PATH_FROM_UTF8_SYMBOL,
    HOST_PATH_FREE_SYMBOL,
    HOST_BYTES_FROM_RAW_SYMBOL,
    HOST_BYTES_VIEW_SYMBOL,
    HOST_BYTES_ALLOC_SYMBOL,
    HOST_BYTES_STORAGE_FREE_SYMBOL,
    HOST_BYTES_COPY_IN_SYMBOL,
    HOST_BYTES_COPY_OUT_SYMBOL,
    HOST_PROCESS_SET_ARGV_SYMBOL,
    HOST_PROCESS_USER_ARGC_SYMBOL,
    HOST_PROCESS_USER_ARG_SYMBOL,
    HOST_ENV_GET_SYMBOL,
    HOST_ENV_SET_SYMBOL,
    HOST_ENV_DELETE_SYMBOL,
    HOST_PROCESS_EXIT_SYMBOL,
    HOST_PROCESS_SET_EXIT_CODE_SYMBOL,
    HOST_PROCESS_GET_EXIT_CODE_SYMBOL,
    HOST_PROCESS_PID_SYMBOL,
    HOST_PROCESS_PPID_SYMBOL,
    HOST_CWD_SYMBOL,
    HOST_CHDIR_SYMBOL,
    HOST_HOSTNAME_SYMBOL,
    HOST_OS_TYPE_SYMBOL,
    HOST_OS_ARCH_SYMBOL,
    HOST_SIGNAL_WATCH_SYMBOL,
    HOST_SIGNAL_RAISE_SYMBOL,
    HOST_SIGNAL_POLL_SYMBOL,
    HOST_NOW_MS_SYMBOL,
    HOST_MONOTONIC_MS_SYMBOL,
    HOST_STDOUT_WRITE_SYMBOL,
    HOST_STDERR_WRITE_SYMBOL,
    HOST_STDIN_READ_LINE_SYMBOL,
    HOST_STDIN_READ_BYTES_SYMBOL,
    HOST_PATH_NORMALIZE_SYMBOL,
    HOST_PATH_JOIN_SYMBOL,
    HOST_PATH_DIRNAME_SYMBOL,
    HOST_PATH_BASENAME_SYMBOL,
    HOST_PATH_EXTNAME_SYMBOL,
    HOST_PATH_IS_ABSOLUTE_SYMBOL,
    HOST_PATH_RESOLVE_SYMBOL,
    HOST_FS_READ_FILE_SYMBOL,
    HOST_FS_READ_TEXT_SYMBOL,
    HOST_FS_WRITE_FILE_SYMBOL,
    HOST_FS_APPEND_FILE_SYMBOL,
    HOST_FS_WRITE_TEXT_SYMBOL,
    HOST_FS_APPEND_TEXT_SYMBOL,
    HOST_FS_EXISTS_SYMBOL,
    HOST_FS_STAT_SYMBOL,
    HOST_FS_MKDIR_SYMBOL,
    HOST_FS_MKDIR_ALL_SYMBOL,
    HOST_FS_READDIR_SYMBOL,
    HOST_FS_RMDIR_SYMBOL,
    HOST_FS_REMOVE_FILE_SYMBOL,
    HOST_FS_RENAME_FILE_SYMBOL,
    HOST_FS_COPY_FILE_SYMBOL,
    HOST_FS_OPEN_SYMBOL,
    HOST_FS_HANDLE_READ_SYMBOL,
    HOST_FS_HANDLE_WRITE_SYMBOL,
    HOST_FS_HANDLE_SEEK_SYMBOL,
    HOST_TCP_LISTEN_SYMBOL,
    HOST_TCP_LOCAL_PORT_SYMBOL,
    HOST_TCP_ACCEPT_SYMBOL,
    HOST_TCP_CONNECT_SYMBOL,
    HOST_TCP_PEER_PORT_SYMBOL,
    HOST_TCP_PEER_ADDRESS_SYMBOL,
    HOST_TCP_READ_SYMBOL,
    HOST_TCP_WRITE_SYMBOL,
    HOST_TCP_SHUTDOWN_SYMBOL,
    HOST_TCP_SET_NONBLOCKING_SYMBOL,
    HOST_IO_WAIT_SYMBOL,
    HOST_IO_CANCEL_SYMBOL,
    HOST_IO_PENDING_SYMBOL,
    HOST_IO_POLL_SYMBOL,
    HOST_TCP_ACCEPT_ASYNC_SYMBOL,
    HOST_TCP_CONNECT_ASYNC_SYMBOL,
    HOST_TCP_READ_ASYNC_SYMBOL,
    HOST_TCP_WRITE_ASYNC_SYMBOL,
    HOST_UDP_BIND_SYMBOL,
    HOST_UDP_LOCAL_PORT_SYMBOL,
    HOST_UDP_SENDTO_SYMBOL,
    HOST_UDP_RECVFROM_SYMBOL,
    HOST_DNS_LOOKUP_SYMBOL,
    HOST_HTTP_PARSE_REQUEST_SYMBOL,
    HOST_HTTP_REQUEST_HEADER_SYMBOL,
    HOST_HTTP_WRITE_RESPONSE_SYMBOL,
    HOST_HTTP_SERVE_STATIC_SYMBOL,
    HOST_HTTP_WRITE_REQUEST_SYMBOL,
    HOST_WS_HANDSHAKE_RESPONSE_SYMBOL,
    HOST_WS_ENCODE_TEXT_SYMBOL,
    HOST_WS_ENCODE_BINARY_SYMBOL,
    HOST_WS_ENCODE_CLOSE_SYMBOL,
    HOST_WS_ENCODE_PING_SYMBOL,
    HOST_WS_ENCODE_PONG_SYMBOL,
    HOST_WS_DECODE_FRAME_SYMBOL,
    HOST_WS_CLIENT_HANDSHAKE_REQUEST_SYMBOL,
    HOST_WS_CLIENT_CHECK_ACCEPT_SYMBOL,
    HOST_WS_ENCODE_TEXT_CLIENT_SYMBOL,
    HOST_HTTP2_CLIENT_PREFACE_SYMBOL,
    HOST_HTTP2_SERVER_PREFACE_SYMBOL,
    HOST_HTTP2_SETTINGS_ACK_SYMBOL,
    HOST_HTTP2_ENCODE_REQUEST_SYMBOL,
    HOST_HTTP2_ENCODE_RESPONSE_SYMBOL,
    HOST_HTTP2_PARSE_REQUEST_SYMBOL,
    HOST_HTTP2_PARSE_RESPONSE_SYMBOL,
    HOST_HTTP2_CLIENT_OPEN_SYMBOL,
    HOST_HTTP2_SERVER_REPLY_SYMBOL,
    HOST_TLS_CLIENT_WRAP_SYMBOL,
    HOST_TLS_SERVER_WRAP_SYMBOL,
    HOST_TLS_READ_SYMBOL,
    HOST_TLS_WRITE_SYMBOL,
    HOST_HTTP_PARSE_RESPONSE_SYMBOL,
    HOST_HTTP_RESPONSE_HEADER_SYMBOL,
    HOST_WORKER_SPAWN_SYMBOL,
    HOST_WORKER_JOIN_SYMBOL,
    HOST_WORKER_TERMINATE_SYMBOL,
    HOST_WORKER_OS_THREAD_SYMBOL,
    HOST_CHANNEL_MAKE_SYMBOL,
    HOST_CHANNEL_SEND_F64_SYMBOL,
    HOST_CHANNEL_SEND_STR_SYMBOL,
    HOST_CHANNEL_SEND_BOOL_SYMBOL,
    HOST_CHANNEL_RECV_F64_SYMBOL,
    HOST_CHANNEL_RECV_STR_SYMBOL,
    HOST_CHANNEL_RECV_BOOL_SYMBOL,
    HOST_CHANNEL_SEND_OBJ_SYMBOL,
    HOST_CHANNEL_RECV_OBJ_SYMBOL,
];

/// Declares used when emitting host I/O calls (H01+).
pub const HOST_DECLARES: &[AbiFn] = &[
    HOST_HANDLE_IS_VALID,
    HOST_HANDLE_CLOSE,
    HOST_PATH_FROM_UTF8,
    HOST_PATH_FREE,
    HOST_BYTES_FROM_RAW,
    HOST_BYTES_VIEW,
    HOST_BYTES_ALLOC,
    HOST_BYTES_STORAGE_FREE,
    HOST_BYTES_COPY_IN,
    HOST_BYTES_COPY_OUT,
    HOST_PROCESS_SET_ARGV,
    HOST_PROCESS_USER_ARGC,
    HOST_PROCESS_USER_ARG,
    HOST_ENV_GET,
    HOST_ENV_SET,
    HOST_ENV_DELETE,
    HOST_PROCESS_EXIT,
    HOST_PROCESS_SET_EXIT_CODE,
    HOST_PROCESS_GET_EXIT_CODE,
    HOST_PROCESS_PID,
    HOST_PROCESS_PPID,
    HOST_CWD,
    HOST_CHDIR,
    HOST_HOSTNAME,
    HOST_OS_TYPE,
    HOST_OS_ARCH,
    HOST_NOW_MS,
    HOST_MONOTONIC_MS,
    HOST_STDOUT_WRITE,
    HOST_STDERR_WRITE,
    HOST_STDIN_READ_LINE,
    HOST_STDIN_READ_BYTES,
    HOST_PATH_NORMALIZE,
    HOST_PATH_JOIN,
    HOST_PATH_DIRNAME,
    HOST_PATH_BASENAME,
    HOST_PATH_EXTNAME,
    HOST_PATH_IS_ABSOLUTE,
    HOST_PATH_RESOLVE,
    HOST_FS_READ_FILE,
    HOST_FS_READ_TEXT,
    HOST_FS_WRITE_FILE,
    HOST_FS_APPEND_FILE,
    HOST_FS_WRITE_TEXT,
    HOST_FS_APPEND_TEXT,
    HOST_FS_EXISTS,
    HOST_FS_STAT,
    HOST_FS_MKDIR,
    HOST_FS_MKDIR_ALL,
    HOST_FS_READDIR,
    HOST_FS_RMDIR,
    HOST_FS_REMOVE_FILE,
    HOST_FS_RENAME_FILE,
    HOST_FS_COPY_FILE,
    HOST_FS_OPEN,
    HOST_FS_HANDLE_READ,
    HOST_FS_HANDLE_WRITE,
    HOST_FS_HANDLE_SEEK,
    HOST_TCP_LISTEN,
    HOST_TCP_LOCAL_PORT,
    HOST_TCP_ACCEPT,
    HOST_TCP_CONNECT,
    HOST_TCP_PEER_PORT,
    HOST_TCP_PEER_ADDRESS,
    HOST_TCP_READ,
    HOST_TCP_WRITE,
    HOST_TCP_SHUTDOWN,
    HOST_TCP_SET_NONBLOCKING,
    HOST_IO_WAIT,
    HOST_IO_CANCEL,
    HOST_IO_PENDING,
    HOST_IO_POLL,
    HOST_TCP_ACCEPT_ASYNC,
    HOST_TCP_CONNECT_ASYNC,
    HOST_TCP_READ_ASYNC,
    HOST_TCP_WRITE_ASYNC,
    HOST_UDP_BIND,
    HOST_UDP_LOCAL_PORT,
    HOST_UDP_SENDTO,
    HOST_UDP_RECVFROM,
    HOST_DNS_LOOKUP,
    HOST_HTTP_PARSE_REQUEST,
    HOST_HTTP_REQUEST_HEADER,
    HOST_HTTP_WRITE_RESPONSE,
    HOST_HTTP_SERVE_STATIC,
    HOST_HTTP_WRITE_REQUEST,
    HOST_HTTP_PARSE_RESPONSE,
    HOST_HTTP_RESPONSE_HEADER,
    HOST_WS_HANDSHAKE_RESPONSE,
    HOST_WS_ENCODE_TEXT,
    HOST_WS_ENCODE_BINARY,
    HOST_WS_ENCODE_CLOSE,
    HOST_WS_ENCODE_PING,
    HOST_WS_ENCODE_PONG,
    HOST_WS_DECODE_FRAME,
    HOST_WS_CLIENT_HANDSHAKE_REQUEST,
    HOST_WS_CLIENT_CHECK_ACCEPT,
    HOST_WS_ENCODE_TEXT_CLIENT,
    HOST_HTTP2_CLIENT_PREFACE,
    HOST_HTTP2_SERVER_PREFACE,
    HOST_HTTP2_SETTINGS_ACK,
    HOST_HTTP2_ENCODE_REQUEST,
    HOST_HTTP2_ENCODE_RESPONSE,
    HOST_HTTP2_PARSE_REQUEST,
    HOST_HTTP2_PARSE_RESPONSE,
    HOST_HTTP2_CLIENT_OPEN,
    HOST_HTTP2_SERVER_REPLY,
    HOST_TLS_CLIENT_WRAP,
    HOST_TLS_SERVER_WRAP,
    HOST_TLS_READ,
    HOST_TLS_WRITE,
    HOST_WORKER_SPAWN,
    HOST_WORKER_JOIN,
    HOST_WORKER_TERMINATE,
    HOST_WORKER_OS_THREAD,
    HOST_CHANNEL_MAKE,
    HOST_CHANNEL_SEND_F64,
    HOST_CHANNEL_SEND_STR,
    HOST_CHANNEL_SEND_BOOL,
    HOST_CHANNEL_RECV_F64,
    HOST_CHANNEL_RECV_STR,
    HOST_CHANNEL_RECV_BOOL,
    HOST_CHANNEL_SEND_OBJ,
    HOST_CHANNEL_RECV_OBJ,
];
